import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    category: "Electronics",
    price: 79.99,
    originalPrice: 129.99,
    rating: 4.8,
    reviewCount: 2341,
    image: "https://m.media-amazon.com/images/I/71YM2N5whtL.jpg",
    badge: "sale",
    description: "Premium sound with 30-hour battery life and active noise cancellation.",
  },
  {
    id: 2,
    name: "Minimalist Leather Watch",
    category: "Accessories",
    price: 149.00,
    rating: 4.6,
    reviewCount: 876,
    image: "https://www.peugeotwatches.com/cdn/shop/products/2059G-FV.jpg?v=1633106380&width=1500",
    badge: "new",
    description: "Slim profile with genuine leather strap and sapphire crystal glass.",
  },
  {
    id: 3,
    name: "Ultralight Running Sneakers",
    category: "Footwear",
    price: 89.95,
    originalPrice: 119.95,
    rating: 4.7,
    reviewCount: 1543,
    image: "https://hips.hearstapps.com/hmg-prod/images/run-lightweight-running-shoes-682b51023eccc.jpg?crop=0.670xw:1.00xh;0.0994xw,0&resize=1200:*",
    badge: "sale",
    description: "Breathable mesh upper with responsive foam cushioning for all-day comfort.",
  },
  {
    id: 4,
    name: "Portable Bluetooth Speaker",
    category: "Electronics",
    price: 59.99,
    rating: 4.5,
    reviewCount: 3210,
    image: "https://cdn.thewirecutter.com/wp-content/media/2024/11/portablebluetoothspeakers-2048px-9130.jpg?width=2048&quality=60&crop=2048:1365&auto=webp",
    badge: "hot",
    description: "360° surround sound with 12-hour playtime and waterproof design.",
  },
  {
    id: 5,
    name: "Organic Cotton Crew Tee",
    category: "Clothing",
    price: 34.00,
    rating: 4.4,
    reviewCount: 654,
    image: "https://matethelabel.com/cdn/shop/files/20250128_LightWork_MateTheLabel_ApparelFlats_SetB_OrganicCottonClassicTee_BON_0410_dc0fb29d-4da1-44bb-b35a-b6bf8b3b3e1e.jpg?v=1743097086",
    description: "Sustainably sourced, pre-washed for a perfectly broken-in feel.",
  },
  {
    id: 6,
    name: "Smart Fitness Tracker Band",
    category: "Electronics",
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.3,
    reviewCount: 1892,
    image: "https://m.media-amazon.com/images/I/71KwGt+7qSL._AC_UF894,1000_QL80_.jpg",
    badge: "sale",
    description: "Track steps, heart rate, sleep, and more with a 7-day battery.",
  },
  {
    id: 7,
    name: "Canvas Weekender Bag",
    category: "Accessories",
    price: 74.00,
    rating: 4.7,
    reviewCount: 421,
    image: "https://buffalojackson.com/cdn/shop/files/Dakota_Round_Duffle_Bag_-_Khaki-1_800x.jpg?v=1725378566",
    badge: "new",
    description: "Waxed canvas with leather trim — perfect for weekend getaways.",
  },
  {
    id: 8,
    name: "Slim Fit Chino Pants",
    category: "Clothing",
    price: 58.00,
    originalPrice: 78.00,
    rating: 4.5,
    reviewCount: 987,
    image: "https://m.media-amazon.com/images/I/61ELTn+o-SL._AC_UY1000_.jpg",
    badge: "sale",
    description: "Stretch-cotton blend for a tailored look with all-day flexibility.",
  },
  {
    id: 9,
    name: "Leather Chelsea Boots",
    category: "Footwear",
    price: 189.00,
    rating: 4.9,
    reviewCount: 312,
    image: "http://lennertson.com/cdn/shop/files/CLOSE_RIDER_GASTON_01.jpg?v=1759421429",
    badge: "limited",
    description: "Full-grain leather with elastic side panels and stacked heel.",
  },
  {
    id: 10,
    name: "Mechanical Keyboard TKL",
    category: "Electronics",
    price: 109.99,
    rating: 4.6,
    reviewCount: 2087,
    image: "https://m.media-amazon.com/images/I/71lQnVCMmXL.jpg",
    description: "Tenkeyless layout with tactile switches and RGB backlighting.",
  },
  {
    id: 11,
    name: "Polarized Aviator Sunglasses",
    category: "Accessories",
    price: 45.00,
    originalPrice: 65.00,
    rating: 4.4,
    reviewCount: 733,
    image: "https://shady-rays.s3.us-east-2.amazonaws.com/assets/ascend/AV-23SN/02.jpg",
    badge: "sale",
    description: "UV400 protection with lightweight metal frame in classic aviator style.",
  },
  {
    id: 12,
    name: "Merino Wool Hoodie",
    category: "Clothing",
    price: 98.00,
    rating: 4.8,
    reviewCount: 445,
    image: "https://i.etsystatic.com/17567182/r/il/b4b016/3215412893/il_fullxfull.3215412893_53k0.jpg",
    badge: "new",
    description: "Naturally temperature-regulating merino wool in a relaxed fit.",
  },
];

export const categories = ["All", "Electronics", "Clothing", "Footwear", "Accessories"];
